### ISSUE TITLE
Wrong Icon gets choosen for Icon request

### ISSUE THREAD

**Issue by shruuub** [Delta-Icons/android#428]
Hello. So I was trying to request an icon, but I saw the link and data of the preformed email was wrong. So I had selected one app (100% sure), but the app below it was choosen. And, after that, the "free" request is not longer available, even though I haven't even sent the email.

**Comment by wokija** [comment]
Hi, this bug was fixed on current CandyBar version. You can install the latest beta available on GitHub which fixes the issue.

**Comment by shruuub** [comment]
Uhm, I downloaded the github version and installed it, but the bug still occurs.

**Comment by wokija** [comment]
Can you try clearing Delta app cache and reopen the app to see if the bug still occurs?

**Comment by shruuub** [comment]
Yes, it does. (I can't file a new request, but it say that I'd already requested the app.(Again the app below the one I want to request)

**Comment by wokija** [comment]
What if you also delete app data?

**Comment by shruuub** [comment]
> What if you also delete app data?

Same problem

**Comment by wokija** [comment]
That's strange. v.1.6.9-beta0 fixes the issue on my phone.

https://github.com/Delta-Icons/android/releases/tag/v1.6.9-beta0

**Comment by shruuub** [comment]
Ahhh, my bad! I downloaded the stable release

**Comment by wokija** [comment]
Stable release should soon follow :)
